### ISSUE TITLE
Laplacian smoothing calls flip_edge?

### ISSUE THREAD

**Issue by krober10nd** [meshpro/optimesh#56]
A simple question: why does the Laplacian smoother flip edges until the triangulation is Delaunay? Laplacian smoothing can occur on all kinds of triangulations...Is there a rationale behind this?

**Comment by nschloe** [comment]
Why not?

**Comment by krober10nd** [comment]
Several reasons: 

1. It's slow O(N^2) at worst case scenario. Sometimes I have a Delaunay mesh I built in parallel and I want to do mesh optimization like Laplacian smoothing. The edge flipping takes longer than the entire execution of the parallel triangulation in the first place defeating the parallelization. 

2. It's not necessary. Laplacian smoothing is supposed to move the nodes to their arithmetic average of their neighbors, nothing more. 

3. I may have some fixed and constraints in the triangulation that are not Delaunay and this will destroy all the work I put in to constrain the edges.

**Comment by nschloe** [comment]
1. It's slow, really? On all meshes I've seen it only takes a tiny fraction of the run time. Note that only very few edges are actually flipped, and checking the need for flips is O(n) I think. Feel free to append a mesh where you experience trouble, I'll be happy to stand corrected.

2. 3. I get those. The main idea behind optimesh is to, well, optimize a mesh. Laplacian smoothing is the worst of them all, but it's getting better with edge flips of course. On the other hand, without the flips it's just one step.

I think I'll add an option for disabling the flips.

**Comment by krober10nd** [comment]
I appreciate it @nschloe 

1. Yea, I am doing this with 500 million to 1 billion vertex meshes so slow is relative. 
2. And yea, I realize that it's just I'm not willing to do dive into parallel mesh improvement just yet so the fastest way to improve the mesh would be in theory Laplacian smoothing. For now, if I have an edge constraint, I just could reject the new point position.

**Comment by nschloe** [comment]
> relative

Relative to the cost of the rest of the algorithm, yes. And I think edge flips are a lot cheaper than the movement of the points. At least that's what I gather from my own measurements.

Feel free to append you mesh and I'll try it out.
