### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by thachdo** [meshpro/optimesh#94]
I got these errors after doing pip install
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement optimesh (from versions: none)
ERROR: No matching distribution found for optimesh
```
How could I resolve this issue, and where is the link to the source?
Thanks.

**Comment by nschloe** [comment]
I'm currently reorganizing my workflow which I why can't find the source here for now.

What's your Python version?

**Comment by thachdo** [comment]
Both python 2 (2.7.17) and 3 (3.6.9) can't install

**Comment by nschloe** [comment]
Yup that's right, Python 2 is unsupported by upstream since more than two years, Python 3.6 four months ago. That's why optimesh (and in face none of my software packages) supports these Python versions.

**Comment by thachdo** [comment]
is there any earlier version that can work with the listed python versions?

**Comment by nschloe** [comment]
No, not yet. If you're interested and have some budgest, I could invest some time in getting it to work though.
