### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ecomodeller** [meshpro/optimesh#95]
It looks like a really neat tool 🎉 , but it lacks a license and thus makes it impossible to use in practise. 😢 

Please take a look at this guide for choosing a license if you intend this library to be publicly available.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

Snip from [PyPI](https://pypi.org/project/optimesh/):
![image](https://user-images.githubusercontent.com/614215/173995470-963ce5c6-4a4f-4ed0-a770-deae6785f338.png)

**Comment by nschloe** [comment]
I'll add one soon.
