### ISSUE TITLE
Is density-preserving ODT still available?

### ISSUE THREAD

**Issue by montehoover** [meshpro/optimesh#97]
The README mentions a density-preserving variant of ODT being available (`--method odt-dp-fp`), but when calling from the command line I get the following error:
`optimesh: error: argument --method/-m: invalid choice: 'odt-dp-fp'`

Is the density-preserving ODT variant still available?

**Comment by nschloe** [comment]
No, it's no longer available. There was a bug that messes with density-preservation, and I haven't looked into it yet, so I've removed the method for now. You could simply try Laplace smoothing.
