### ISSUE TITLE
Can I still use optimesh after 2023/1/1?

### ISSUE THREAD

**Issue by loganbvh** [meshpro/optimesh#98]
Hi, I have begun seeing the following messages when using `optimesh` version 0.9.4. Can you explain what this means for academic users of optimesh?

```
From [b]Jan 1, 2023[/b], meshplex will require a meshpro license to run. See https://github.com/meshpro for details.
From [b]Jan 1, 2023[/b], some features of optimesh (e.g., {which}) will require a meshpro license to run. See https://github.com/meshpro for details.
```

**Comment by nschloe** [comment]
Ah, I'm just seeing this now. I've pushed back the release a bit, so if you'll just upgrade, you'll be fine. Will release further details later.

**Comment by loganbvh** [comment]
Thanks. For now, I've decided to just use Laplacian smoothing and remove optimesh as a dependency from my projects
